version: '3.9'
services:
  arangodb_db:
    image: arangodb:3.11
    environment:
      ARANGO_ROOT_PASSWORD: root
    ports:
      - '8529:8529'
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps

volumes:
  arangodb_data_container:
  arangodb_apps_data_container:
